<?php

/**
 * Prevent Direct Access
 */
defined( 'ABSPATH' ) or die( "Restricted access!" );

/**
 * Register text domain
 */
function spacexchimp_p011_textdomain() {
    load_plugin_textdomain( SPACEXCHIMP_P011_TEXT, false, SPACEXCHIMP_P011_DIR . '/languages/' );
}
add_action( 'init', 'spacexchimp_p011_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WordPress Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 */
function spacexchimp_p011_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=' . SPACEXCHIMP_P011_SLUG ) . '">' . __( 'Settings', SPACEXCHIMP_P011_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_' . SPACEXCHIMP_P011_BASE, 'spacexchimp_p011_settings_link' );

/**
 * Print additional links to plugin meta row
 */
function spacexchimp_p011_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, SPACEXCHIMP_P011_SLUG . '.php' ) !== false ) {

        $new_links = array(
                           'documentation' => '<a href="https://docs.spacexchimp.com/product/plugin/my-custom-functions-pro/instructions.html" target="_blank">' . __( 'Documentation', SPACEXCHIMP_P011_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', 'spacexchimp_p011_plugin_row_meta', 10, 2 );

/**
 * Register a submenu item in the top-level menu item "Settings"
 */
function spacexchimp_p011_register_submenu_page() {

    $page_title  = SPACEXCHIMP_P011_NAME;
    $menu_title  = __( 'PHP Inserter PRO', SPACEXCHIMP_P011_TEXT );
    $capability  = 'manage_options';
    $menu_slug   = SPACEXCHIMP_P011_SLUG;
    $function    = 'spacexchimp_p011_render_submenu_page';

    add_options_page( $page_title, $menu_title, $capability, $menu_slug, $function );
}
add_action( 'admin_menu', 'spacexchimp_p011_register_submenu_page' );

/**
 * Register settings
 */
function spacexchimp_p011_register_settings() {
    register_setting( SPACEXCHIMP_P011_SETTINGS . '_settings_group', SPACEXCHIMP_P011_SETTINGS . '_settings' );
    register_setting( SPACEXCHIMP_P011_SETTINGS . '_settings_group_si', SPACEXCHIMP_P011_SETTINGS . '_service_info' );
    register_setting( SPACEXCHIMP_P011_SETTINGS . '_settings_group_info', SPACEXCHIMP_P011_SETTINGS . '_info' );
    register_setting( SPACEXCHIMP_P011_SETTINGS . '_settings_group', SPACEXCHIMP_P011_SETTINGS . '_error' );
}
add_action( 'admin_init', 'spacexchimp_p011_register_settings' );

/**
 * Branded footer text on the plugin's settings page
 */
function spacexchimp_p011_admin_footer_text() {

    // Get current screen data
    $current_screen = get_current_screen();

    // Return if the page is not a settings page of this plugin
    $settings_page = 'settings_page_' . SPACEXCHIMP_P011_SLUG;
    if ( $settings_page != $current_screen->id ) return;

    // Filter footer text
    function spacexchimp_p011_new_admin_footer_text() {
        $year = date('Y');
        return "Copyright &copy; " . $year . " <a href='https://www.spacexchimp.com' target='_blank'>Space X-Chimp</a> | Click <a href='https://www.spacexchimp.com/store.html' target='_blank'>here</a> to see our other products.";
    }
    add_filter( 'admin_footer_text', 'spacexchimp_p011_new_admin_footer_text', 11 );
}
add_action( 'current_screen', 'spacexchimp_p011_admin_footer_text' );

/**
 * Runs during the plugin activation
 */
function spacexchimp_p011_activation() {

    // Read the plugin service information from the database and put it into an array
    $info = get_option( SPACEXCHIMP_P011_SETTINGS . '_service_info' );

    // Make the "$info" array if the plugin service information in the database is not exist
    if ( ! is_array( $info ) ) $info = array();

    // Get the activation date of the plugin from the database
    $activation_date = !empty( $info['activation_date'] ) ? $info['activation_date'] : '';

    if ( $activation_date == '' ) {
        $info['activation_date'] = time();
        update_option( SPACEXCHIMP_P011_SETTINGS . '_service_info', $info );
    }
}
register_activation_hook( SPACEXCHIMP_P011_FILE, 'spacexchimp_p011_activation' );

/**
 * Delete options on uninstall
 */
function spacexchimp_p011_uninstall() {
    delete_option( SPACEXCHIMP_P011_SETTINGS . '_settings' );
    delete_option( SPACEXCHIMP_P011_SETTINGS . '_error' );
}
register_uninstall_hook( SPACEXCHIMP_P011_FILE, 'spacexchimp_p011_uninstall' );
